name: methylseqnet
channels:
  - nanoporetech
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.11
  - pip
  - htslib
  - whatshap
  - dipcall
  - bcftools
  - isoseq
  - pb-cpg-tools
  - modkit=0.2.4
  - pip:
    - -e .