[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "methylseqnet"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0,<2.7.0",
    "biopython>=1.83",
    "scikit-learn>=1.7.2",
    "captum>=0.7.0",
    "scipy>=1.13.0",
    "gin-config>=0.5.0",
    "nvidia-ml-py>=13.595.45",
    "pysam>=0.22.1",
    "lightning>=2.4.0",
    "h5py>=3.11.0",
    "pyBigWig>=0.3.22",
    "wandb>=0.21",
    "borzoi-pytorch>=0.4.1",
    "basenji2-pytorch>=0.1.2",
    "alphagenome-pytorch>=0.1.0",
    "huggingface-hub>=0.20.0",
#    "numpy<2.0.0",
    "numpy>=1.26.4",
    "psutil>=5.9.8",
    "tqdm>=4.66.4",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.package-data]
methylseqnet = ["configs/*.toml", "configs/*.toml.example"]

[project.scripts]
methylseqnet-train = "methylseqnet.train:cli"
methylseqnet-predict = "methylseqnet.predict:main"
methylseqnet-preprocess = "methylseqnet.preprocess:main"
methylseqnet-peaks = "methylseqnet.peaks:main"
methylseqnet-insert-motifs = "methylseqnet.motifs:main"