[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "methylseqnet"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "biopython",
    "scikit-learn",
    "captum",
    "modisco-lite",
    "scipy",
    "gin-config",
    "nvidia-ml-py",
    "logomaker",
    "pysam",
    "pytest",
    "lightning",
    "h5py",
    "pyBigWig",
    "wandb>=0.21",
    "borzoi-pytorch",
    "basenji2-pytorch>=0.1.2",
    "umap-learn",
    "numba>=0.58.0",
    "numpy<2.0.0",
    "psutil",
    "openpyxl",
    "ipykernel",
    "tqdm",
    "ipywidgets",
    "seaborn",
    "pyliftover",
]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.package-data]
methylseqnet = ["configs/*.toml", "configs/*.toml.example"]